services:

  web:
    build:
      context: .
      target: development
    image: bookmark-laravel-app:latest
    container_name: bookmark-laravel-app-dev
    env_file: .env.dev
    restart: unless-stopped
    ports:
      - "8080:80"
    develop:
      watch:
        - path: ./
          target: .
          action: sync
        - path: Dockerfile
          action: rebuild
        - path: package.json
          action: rebuild
        - path: composer.json
          action: rebuild
    depends_on:
      - mysql_db
    #   - cache

  mysql_db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
        - MYSQL_ROOT_PASSWORD=4298
    volumes:
        - mysqldb-data:/var/lib/mysql
      
  # cache:
  #   image: redis:8-alpine
  #   restart: unless-stopped
  #   # ports: DOn't need it i will not connect outside docker
  #   #   - "6379:6379"
  #   volumes:
  #     - cache-data:/data
  #   command: ["redis-server", "--appendonly", "yes"]

volumes:
  mysqldb-data:
  cache-data:
    
      
      
      